import { useState, type ReactNode } from 'react'
import { Link, Navigate, Outlet, useNavigate, useParams } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'

import { useAuth } from '../auth/AuthContext'
import { ApiError } from '../../lib/api'
import { projectKeys, projectsApi, type Project, type Suite } from './api'

const projectSchema = z.object({ name: z.string().trim().min(2).max(120), description: z.string().max(2000).optional(), targetOrigin: z.string().url() })
type ProjectForm = z.infer<typeof projectSchema>
const suiteSchema = z.object({ name: z.string().trim().min(2).max(160), description: z.string().max(2000).optional() })
type SuiteForm = z.infer<typeof suiteSchema>

export function ProtectedRoute() {
  const { user, providers, loading } = useAuth()
  if (loading) return <section className="card"><p>Loading your workspace…</p></section>
  if (!providers?.enabled) return <Navigate to="/" replace />
  if (!user) return <Navigate to="/login" replace />
  return <Outlet />
}

export function ProjectsPage() {
  const [search, setSearch] = useStateValue('')
  const query = useQuery({ queryKey: projectKeys.list(search), queryFn: () => projectsApi.list(search) })
  return <section className="page-stack"><div className="page-heading"><div><p className="eyebrow">Workspace</p><h1>Projects</h1><p className="lede">Organize targets, test suites, and reusable variables.</p></div><Link className="button" to="/projects/new">New project</Link></div><label className="search-field">Filter projects<input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search by name" /></label>{query.isPending && <div className="card">Loading projects…</div>}{query.isError && <div className="card form-error">{query.error instanceof ApiError ? query.error.message : 'Unable to load projects'}</div>}<div className="project-grid">{query.data?.content.map(project => <ProjectCard key={project.id} project={project} />)}</div>{query.data && query.data.content.length === 0 && <div className="card">No projects match this filter.</div>}</section>
}

function ProjectCard({ project }: { project: Project }) { return <Link className="card project-card" to={`/projects/${project.id}`}><div><p className="eyebrow">{project.status}</p><h2>{project.name}</h2><p>{project.description || 'No description yet.'}</p></div><span className="muted">{project.targetOrigin}</span></Link> }

export function NewProjectPage() {
  const navigate = useNavigate(); const client = useQueryClient()
  const form = useForm<ProjectForm>({ resolver: zodResolver(projectSchema), defaultValues: { name: '', description: '', targetOrigin: '' } })
  const mutation = useMutation({ mutationFn: projectsApi.create, onSuccess: project => { client.invalidateQueries({ queryKey: projectKeys.all }); navigate(`/projects/${project.id}`) } })
  return <section className="card auth-card"><p className="eyebrow">Projects</p><h1>Create project</h1><form className="form-stack" onSubmit={form.handleSubmit(values => mutation.mutate(values))}><Field label="Name" error={form.formState.errors.name?.message}><input {...form.register('name')} /></Field><Field label="Description" error={form.formState.errors.description?.message}><textarea {...form.register('description')} rows={4} /></Field><Field label="Target origin" help="Use an origin in TARGET_ALLOWED_ORIGINS, for example https://shop.example.test." error={form.formState.errors.targetOrigin?.message}><input type="url" placeholder="https://shop.example.test" {...form.register('targetOrigin')} /></Field>{mutation.isError && <p className="form-error">{mutation.error instanceof Error ? mutation.error.message : 'Unable to create project'}</p>}<div className="inline-actions"><button type="submit" disabled={mutation.isPending}>{mutation.isPending ? 'Creating…' : 'Create project'}</button><Link className="button secondary" to="/projects">Cancel</Link></div></form></section>
}

export function ProjectLayout() { const { projectId } = useParams(); if (!projectId) return <Navigate to="/projects" replace />; return <Outlet /> }

export function ProjectOverviewPage() {
  const { projectId = '' } = useParams(); const query = useQuery({ queryKey: projectKeys.detail(projectId), queryFn: () => projectsApi.get(projectId) }); const archive = useMutation({ mutationFn: () => projectsApi.archive(projectId), onSuccess: () => query.refetch() })
  if (query.isPending) return <div className="card">Loading project…</div>; if (query.isError || !query.data) return <div className="card form-error">Unable to load this project.</div>; const project = query.data
  return <section className="page-stack"><div className="page-heading"><div><p className="eyebrow">Project</p><h1>{project.name}</h1><p className="lede">{project.description || 'Build and maintain reliable browser checks.'}</p></div><div className="inline-actions"><Link className="button secondary" to="/projects">All projects</Link>{project.status === 'ACTIVE' && <button className="secondary" onClick={() => archive.mutate()} disabled={archive.isPending}>Archive</button>}</div></div><div className="card project-summary"><p><strong>Target:</strong> {project.targetOrigin}</p><p><strong>Status:</strong> {project.status}</p><p><strong>Version:</strong> {project.version}</p></div><nav className="subnav" aria-label="Project sections"><Link to=".">Overview</Link><Link to="suites">Suites</Link><Link to="variables">Variables</Link><Link to="members">Members</Link></nav><Outlet /></section>
}

export function SuitesPage() {
  const { projectId = '' } = useParams(); const client = useQueryClient(); const query = useQuery({ queryKey: projectKeys.suites(projectId), queryFn: () => projectsApi.suites(projectId) }); const form = useForm<SuiteForm>({ resolver: zodResolver(suiteSchema), defaultValues: { name: '', description: '' } }); const mutation = useMutation({ mutationFn: projectsApi.createSuite.bind(null, projectId), onSuccess: () => { form.reset(); client.invalidateQueries({ queryKey: projectKeys.suites(projectId) }) } })
  return <section className="page-stack"><div className="card"><h2>New suite</h2><form className="inline-form" onSubmit={form.handleSubmit(values => mutation.mutate(values))}><input aria-label="Suite name" placeholder="Suite name" {...form.register('name')} /><input aria-label="Suite description" placeholder="Description (optional)" {...form.register('description')} /><button type="submit" disabled={mutation.isPending}>Add suite</button></form>{form.formState.errors.name && <p className="form-error">{form.formState.errors.name.message}</p>}</div><div className="project-grid">{query.data?.map(suite => <SuiteCard key={suite.id} suite={suite} projectId={projectId} />)}</div></section>
}
function SuiteCard({ suite, projectId }: { suite: Suite; projectId: string }) { return <Link className="card project-card" to={`/projects/${projectId}/suites/${suite.id}`}><p className="eyebrow">Suite</p><h2>{suite.name}</h2><p>{suite.description || 'No description yet.'}</p></Link> }

export function VariablesPage() {
  const { projectId = '' } = useParams(); const client = useQueryClient(); const query = useQuery({ queryKey: projectKeys.variables(projectId), queryFn: () => projectsApi.variables(projectId) }); const form = useForm({ defaultValues: { key: '', secret: false, value: '' } }); const mutation = useMutation({ mutationFn: projectsApi.createVariable.bind(null, projectId), onSuccess: () => { form.reset(); client.invalidateQueries({ queryKey: projectKeys.variables(projectId) }) } });
  return <section className="page-stack"><div className="card"><h2>Add variable</h2><p className="form-help">Secret values are write-only and require the server feature flag and key.</p><form className="inline-form" onSubmit={form.handleSubmit(values => mutation.mutate(values))}><input aria-label="Variable key" placeholder="BASE_URL" {...form.register('key')} /><input aria-label="Variable value" placeholder="Value" type={form.watch('secret') ? 'password' : 'text'} {...form.register('value')} /><label className="checkbox"><input type="checkbox" {...form.register('secret')} /> Secret</label><button type="submit" disabled={mutation.isPending}>Save variable</button></form></div><div className="card"><h2>Variables</h2>{query.data?.length ? <ul className="resource-list">{query.data.map(variable => <li key={variable.key}><span><strong>{variable.key}</strong>{variable.secret && <span className="muted"> · secret</span>}</span><span>{variable.secret ? '••••••••' : variable.value}</span><button className="link-button" onClick={() => projectsApi.deleteVariable(projectId, variable.key).then(() => client.invalidateQueries({ queryKey: projectKeys.variables(projectId) }))}>Remove</button></li>)}</ul> : <p className="muted">No variables yet.</p>}</div></section>
}

export function MembersPage() {
  const { projectId = '' } = useParams(); const client = useQueryClient(); const query = useQuery({ queryKey: projectKeys.members(projectId), queryFn: () => projectsApi.members(projectId) }); const form = useForm({ defaultValues: { email: '', role: 'EDITOR' } }); const mutation = useMutation({ mutationFn: projectsApi.addMember.bind(null, projectId), onSuccess: () => { form.reset(); client.invalidateQueries({ queryKey: projectKeys.members(projectId) }) } });
  return <section className="page-stack"><div className="card"><h2>Add member</h2><form className="inline-form" onSubmit={form.handleSubmit(values => mutation.mutate(values))}><input aria-label="Member email" type="email" placeholder="person@example.com" {...form.register('email')} /><select aria-label="Member role" {...form.register('role')}><option>EDITOR</option><option>VIEWER</option><option>ADMIN</option></select><button type="submit" disabled={mutation.isPending}>Add member</button></form></div><div className="card"><h2>Members</h2><ul className="resource-list">{query.data?.map(member => <li key={member.userId}><span><strong>{member.displayName}</strong><span className="muted"> · {member.email}</span></span><span>{member.role}</span></li>)}</ul></div></section>
}

export function SuitePage() { const { projectId = '', suiteId = '' } = useParams(); const query = useQuery({ queryKey: projectKeys.cases(projectId, suiteId), queryFn: () => projectsApi.cases(projectId, suiteId) }); return <section className="card"><p className="eyebrow">Suite</p><h2>Test cases</h2><Link className="button" to={`/projects/${projectId}/suites/${suiteId}/cases/new`}>New case</Link><ul className="resource-list">{query.data?.map(testCase => <li key={testCase.id}><Link to={`/projects/${projectId}/suites/${suiteId}/cases/${testCase.id}`}>{testCase.name}</Link><span className="muted">{testCase.status} · {testCase.priority}</span></li>)}</ul></section> }
export function NewCasePage() { const { projectId = '', suiteId = '' } = useParams(); const navigate = useNavigate(); const form = useForm({ defaultValues: { name: '', description: '', status: 'DRAFT', priority: 'MEDIUM', tags: '', retryCount: 0, dataIsolation: true } }); const mutation = useMutation({ mutationFn: (values: Record<string, unknown>) => projectsApi.createCase(projectId, suiteId, { ...values, steps: [] }), onSuccess: testCase => navigate(`/projects/${projectId}/suites/${suiteId}/cases/${testCase.id}`) }); return <section className="card"><p className="eyebrow">Test case</p><h1>New case</h1><form className="form-stack" onSubmit={form.handleSubmit(values => mutation.mutate(values))}><Field label="Name"><input {...form.register('name', { required: true })} /></Field><Field label="Description"><textarea rows={4} {...form.register('description')} /></Field><div className="inline-form"><label>Status<select {...form.register('status')}><option>DRAFT</option><option>READY</option></select></label><label>Priority<select {...form.register('priority')}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label></div><button type="submit" disabled={mutation.isPending}>Create case</button></form></section> }
export function CasePage() { const { projectId = '', suiteId = '', caseId = '' } = useParams(); const client = useQueryClient(); const query = useQuery({ queryKey: ['case', projectId, suiteId, caseId], queryFn: () => projectsApi.getCase(projectId, suiteId, caseId) }); const mutation = useMutation({ mutationFn: (values: Record<string, unknown>) => projectsApi.updateCase(projectId, suiteId, caseId, { ...values, projectVersion: query.data?.version, steps: query.data?.steps ?? [] }), onSuccess: () => client.invalidateQueries({ queryKey: ['case', projectId, suiteId, caseId] }) }); const form = useForm({ values: query.data ? { name: query.data.name, description: query.data.description ?? '', status: query.data.status, priority: query.data.priority, tags: query.data.tags ?? '', retryCount: query.data.retryCount, dataIsolation: query.data.dataIsolation } : undefined }); if (query.isPending) return <div className="card">Loading case…</div>; if (query.isError || !query.data) return <div className="card form-error">Unable to load this case.</div>; return <section className="card"><p className="eyebrow">Test case editor</p><h1>{query.data.name}</h1><p className="form-help">Steps are replaced as one aggregate update and conflicts require a reload.</p><form className="form-stack" onSubmit={form.handleSubmit(values => mutation.mutate(values))}><Field label="Name"><input {...form.register('name', { required: true })} /></Field><Field label="Description"><textarea rows={4} {...form.register('description')} /></Field><div className="inline-form"><label>Status<select {...form.register('status')}><option>DRAFT</option><option>READY</option><option>ARCHIVED</option></select></label><label>Priority<select {...form.register('priority')}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label></div><button type="submit" disabled={mutation.isPending}>{mutation.isPending ? 'Saving…' : 'Save case'}</button></form><h2>Ordered steps</h2><ol>{query.data.steps.map(step => <li key={step.id ?? step.position}>{step.action}{step.locatorValue ? ` · ${step.locatorValue}` : ''}</li>)}</ol></section> }

function Field({ label, help, error, children }: { label: string; help?: string; error?: string; children: ReactNode }) { return <label>{label}{children}{help && <small className="form-help">{help}</small>}{error && <small className="form-error">{error}</small>}</label> }
function useStateValue<T>(initial: T) { const [value, setValue] = useState(initial); return [value, setValue] as const }
