package com.megumi.testops.project.service;

import java.time.Instant;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.UUID;

import org.springframework.http.HttpStatus;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.megumi.testops.auth.domain.UserEntity;
import com.megumi.testops.project.api.ProjectDtos;
import com.megumi.testops.project.domain.ProjectEntity;
import com.megumi.testops.project.domain.TestCaseEntity;
import com.megumi.testops.project.domain.TestStepEntity;
import com.megumi.testops.project.domain.TestSuiteEntity;
import com.megumi.testops.project.repository.TestCaseRepository;
import com.megumi.testops.project.repository.TestStepRepository;
import com.megumi.testops.project.repository.TestSuiteRepository;
import com.megumi.testops.shared.api.ApiException;

@Service
public class DefinitionService {
    private static final Set<String> ACTIONS = Set.of("NAVIGATE", "CLICK", "FILL", "CLEAR", "SELECT_OPTION", "CHECK", "UNCHECK", "WAIT", "WAIT_VISIBLE", "WAIT_HIDDEN", "PRESS", "HOVER", "ASSERT_TEXT_EQUALS", "ASSERT_TEXT_CONTAINS", "ASSERT_VISIBLE", "ASSERT_HIDDEN", "ASSERT_VALUE", "ASSERT_CHECKED", "ASSERT_ENABLED", "ASSERT_DISABLED", "ASSERT_ATTRIBUTE", "ASSERT_COUNT", "ASSERT_URL_CONTAINS", "ASSERT_URL_EQUALS", "TAKE_SCREENSHOT");
    private static final Set<String> LOCATOR_ACTIONS = Set.of("CLICK", "FILL", "CLEAR", "SELECT_OPTION", "CHECK", "UNCHECK", "WAIT_VISIBLE", "WAIT_HIDDEN", "PRESS", "HOVER", "ASSERT_TEXT_EQUALS", "ASSERT_TEXT_CONTAINS", "ASSERT_VISIBLE", "ASSERT_HIDDEN", "ASSERT_VALUE", "ASSERT_CHECKED", "ASSERT_ENABLED", "ASSERT_DISABLED", "ASSERT_ATTRIBUTE", "ASSERT_COUNT");
    private static final Set<String> LOCATOR_TYPES = Set.of("ROLE", "LABEL", "TEST_ID", "TEXT", "TEXT_EXACT", "PLACEHOLDER", "ALT_TEXT", "TITLE", "CSS", "XPATH");
    private final TestSuiteRepository suites; private final TestCaseRepository cases; private final TestStepRepository steps; private final ProjectAccessService access;
    public DefinitionService(TestSuiteRepository suites, TestCaseRepository cases, TestStepRepository steps, ProjectAccessService access) { this.suites = suites; this.cases = cases; this.steps = steps; this.access = access; }

    @Transactional(readOnly = true)
    public List<ProjectDtos.SuiteResponse> suites(Jwt jwt, UUID projectId) { return suites(jwt, projectId, "ACTIVE"); }
    @Transactional(readOnly = true)
    public List<ProjectDtos.SuiteResponse> suites(Jwt jwt, UUID projectId, String lifecycle) { UserEntity user = access.user(jwt); ProjectEntity project = access.project(projectId); if (!access.globalAdmin(jwt)) access.membership(project, user); return findSuites(projectId, lifecycle(lifecycle)).stream().map(this::suiteResponse).toList(); }
    @Transactional(readOnly = true)
    public ProjectDtos.SuiteResponse getSuite(Jwt jwt, UUID projectId, UUID suiteId) { UserEntity user = access.user(jwt); ProjectEntity project = access.project(projectId); if (!access.globalAdmin(jwt)) access.membership(project, user); return suiteResponse(suite(projectId, suiteId)); }
    @Transactional
    public ProjectDtos.SuiteResponse createSuite(Jwt jwt, UUID projectId, ProjectDtos.SuiteRequest request) { UserEntity user = access.user(jwt); ProjectEntity project = access.project(projectId); access.requireProjectRole(project, user, jwt, Set.of("PROJECT_MANAGER", "TEST_MANAGER")); ensureActive(project); String name = request.name().trim(); if (activeSuiteNameExists(projectId, name)) throw error(HttpStatus.CONFLICT, "suite_name_taken", "Suite name is already in use"); TestSuiteEntity suite = suites.save(new TestSuiteEntity(project, name, trim(request.description()), user, Instant.now())); return suiteResponse(suite); }
    @Transactional
    public ProjectDtos.SuiteResponse updateSuite(Jwt jwt, UUID projectId, UUID suiteId, ProjectDtos.SuiteRequest request) { UserEntity user = access.user(jwt); ProjectEntity project = access.project(projectId); access.requireProjectRole(project, user, jwt, Set.of("PROJECT_MANAGER", "TEST_MANAGER")); ensureActive(project); TestSuiteEntity suite = activeSuite(projectId, suiteId); requireVersion(suite.getVersion(), request.projectVersion()); String name = request.name().trim(); if (!name.equalsIgnoreCase(suite.getName()) && activeSuiteNameExists(projectId, name)) throw error(HttpStatus.CONFLICT, "suite_name_taken", "Suite name is already in use"); suite.update(name, trim(request.description()), Instant.now()); return suiteResponse(suite); }
    @Transactional
    public void archiveSuite(Jwt jwt, UUID projectId, UUID suiteId) { archiveSuite(jwt, projectId, suiteId, null); }
    @Transactional
    public ProjectDtos.SuiteResponse archiveSuite(Jwt jwt, UUID projectId, UUID suiteId, Long version) { UserEntity user = access.user(jwt); ProjectEntity project = access.project(projectId); access.requireProjectRole(project, user, jwt, Set.of("PROJECT_MANAGER", "TEST_MANAGER")); ensureActive(project); TestSuiteEntity suite = activeSuite(projectId, suiteId); requireVersion(suite.getVersion(), version); suite.archive(user, Instant.now()); suites.saveAndFlush(suite); return suiteResponse(suite); }
    @Transactional
    public ProjectDtos.SuiteResponse restoreSuite(Jwt jwt, UUID projectId, UUID suiteId, ProjectDtos.RestoreRequest request) { UserEntity user = access.user(jwt); ProjectEntity project = access.project(projectId); access.requireProjectRole(project, user, jwt, Set.of("PROJECT_MANAGER", "TEST_MANAGER")); ensureActive(project); TestSuiteEntity suite = suite(projectId, suiteId); if (!"ARCHIVED".equals(suite.getStatus())) throw error(HttpStatus.CONFLICT, "suite_not_archived", "Only archived suites can be restored"); requireVersion(suite.getVersion(), request.version()); String name = restoredName(request.name(), suite.getName(), 160); if (activeSuiteNameExists(projectId, name)) throw error(HttpStatus.CONFLICT, "suite_restore_name_conflict", "An active suite already uses this name"); suite.restore(name, Instant.now()); suites.saveAndFlush(suite); return suiteResponse(suite); }
    @Transactional(readOnly = true)
    public List<ProjectDtos.CaseResponse> cases(Jwt jwt, UUID projectId, UUID suiteId) { return cases(jwt, projectId, suiteId, "ACTIVE"); }
    @Transactional(readOnly = true)
    public List<ProjectDtos.CaseResponse> cases(Jwt jwt, UUID projectId, UUID suiteId, String lifecycle) { UserEntity user = access.user(jwt); ProjectEntity project = access.project(projectId); if (!access.globalAdmin(jwt)) access.membership(project, user); TestSuiteEntity suite = suite(projectId, suiteId); return findCases(suite.getId(), lifecycle(lifecycle)).stream().map(this::caseResponse).toList(); }
    @Transactional(readOnly = true)
    public ProjectDtos.CaseResponse getCase(Jwt jwt, UUID projectId, UUID suiteId, UUID caseId) { UserEntity user = access.user(jwt); ProjectEntity project = access.project(projectId); if (!access.globalAdmin(jwt)) access.membership(project, user); suite(projectId, suiteId); TestCaseEntity testCase = testCase(suiteId, caseId); return caseResponse(testCase); }
    @Transactional
    public ProjectDtos.CaseResponse createCase(Jwt jwt, UUID projectId, UUID suiteId, ProjectDtos.CaseRequest request) { UserEntity user = access.user(jwt); ProjectEntity project = access.project(projectId); access.requireProjectRole(project, user, jwt, Set.of("PROJECT_MANAGER", "TEST_MANAGER")); ensureActive(project); TestSuiteEntity suite = activeSuite(projectId, suiteId); String name = request.name().trim(); if (activeCaseNameExists(suiteId, name)) throw error(HttpStatus.CONFLICT, "case_name_taken", "Case name is already in use"); String caseStatus = status(request.status()); validateCase(request, caseStatus); TestCaseEntity entity = cases.save(new TestCaseEntity(suite, name, trim(request.description()), caseStatus, priority(request.priority()), trim(request.tags()), request.retryCount() == null ? 0 : request.retryCount(), request.dataIsolation() == null || request.dataIsolation(), user, Instant.now())); replaceSteps(entity, request.steps(), "READY".equals(caseStatus)); return caseResponse(entity); }
    @Transactional
    public ProjectDtos.CaseResponse updateCase(Jwt jwt, UUID projectId, UUID suiteId, UUID caseId, ProjectDtos.CaseRequest request) { UserEntity user = access.user(jwt); ProjectEntity project = access.project(projectId); access.requireProjectRole(project, user, jwt, Set.of("PROJECT_MANAGER", "TEST_MANAGER")); ensureActive(project); activeSuite(projectId, suiteId); TestCaseEntity entity = testCase(suiteId, caseId); if ("ARCHIVED".equals(entity.getStatus())) throw error(HttpStatus.CONFLICT, "case_archived", "Archived cases are read-only"); requireVersion(entity.getVersion(), request.projectVersion()); String caseStatus = status(request.status()); validateCase(request, caseStatus); String name = request.name().trim(); if (!name.equalsIgnoreCase(entity.getName()) && activeCaseNameExists(suiteId, name)) throw error(HttpStatus.CONFLICT, "case_name_taken", "Case name is already in use"); entity.update(name, trim(request.description()), caseStatus, priority(request.priority()), trim(request.tags()), request.retryCount() == null ? 0 : request.retryCount(), request.dataIsolation() == null || request.dataIsolation(), Instant.now()); replaceSteps(entity, request.steps(), "READY".equals(caseStatus)); return caseResponse(entity); }
    @Transactional
    public ProjectDtos.CaseResponse archiveCase(Jwt jwt, UUID projectId, UUID suiteId, UUID caseId, Long version) { UserEntity user = access.user(jwt); ProjectEntity project = access.project(projectId); access.requireProjectRole(project, user, jwt, Set.of("PROJECT_MANAGER", "TEST_MANAGER")); ensureActive(project); activeSuite(projectId, suiteId); TestCaseEntity entity = testCase(suiteId, caseId); if ("ARCHIVED".equals(entity.getStatus())) throw error(HttpStatus.CONFLICT, "case_archived", "Case is already archived"); requireVersion(entity.getVersion(), version); entity.archive(user, Instant.now()); cases.saveAndFlush(entity); return caseResponse(entity); }
    @Transactional
    public ProjectDtos.CaseResponse restoreCase(Jwt jwt, UUID projectId, UUID suiteId, UUID caseId, ProjectDtos.RestoreRequest request) { UserEntity user = access.user(jwt); ProjectEntity project = access.project(projectId); access.requireProjectRole(project, user, jwt, Set.of("PROJECT_MANAGER", "TEST_MANAGER")); ensureActive(project); activeSuite(projectId, suiteId); TestCaseEntity entity = testCase(suiteId, caseId); if (!"ARCHIVED".equals(entity.getStatus())) throw error(HttpStatus.CONFLICT, "case_not_archived", "Only archived cases can be restored"); requireVersion(entity.getVersion(), request.version()); String name = restoredName(request.name(), entity.getName(), 200); if (activeCaseNameExists(suiteId, name)) throw error(HttpStatus.CONFLICT, "case_restore_name_conflict", "An active case already uses this name"); entity.restore(name, Instant.now()); cases.saveAndFlush(entity); return caseResponse(entity); }

    private void replaceSteps(TestCaseEntity entity, List<ProjectDtos.StepRequest> input, boolean ready) { steps.deleteByTestCaseId(entity.getId()); if (input == null) return; steps.flush(); List<ProjectDtos.StepRequest> ordered = input.stream().sorted(Comparator.comparingInt(ProjectDtos.StepRequest::position)).toList(); java.util.Set<Integer> positions = new java.util.HashSet<>(); if (ordered.size() > 100) throw error(HttpStatus.BAD_REQUEST, "too_many_steps", "A test case may contain at most 100 steps"); for (int i = 0; i < ordered.size(); i++) { ProjectDtos.StepRequest step = ordered.get(i); if (!positions.add(step.position()) || step.position() != i) throw error(HttpStatus.BAD_REQUEST, "invalid_step_order", "Steps must have unique contiguous positions"); if (step.position() != 0 && hasContextSettings(step)) throw stepError(step, "context", "context_settings_must_be_first", "Viewport, locale, and timezone settings belong on the first step"); if (ready) validateStep(step); else validateDraftStep(step); String action = canonicalAction(step.action()); if ("WAIT".equals(action) && step.locatorType() != null && !step.locatorType().isBlank()) action = "WAIT_VISIBLE"; steps.save(new TestStepEntity(entity, step.position(), action, trim(step.locatorType()), trim(step.locatorValue()), trim(step.locatorRole()), step.locatorIndex(), step.inputValue(), trim(step.expectedValue()), step.timeoutMs(), step.viewportWidth(), step.viewportHeight(), trim(step.locale()), trim(step.timezoneId()), Instant.now())); } }
    static void validateDraftStep(ProjectDtos.StepRequest step) { validateStepValues(step, false); }
    static void validateStep(ProjectDtos.StepRequest step) { validateStepValues(step, true); }
    private static void validateStepValues(ProjectDtos.StepRequest step, boolean complete) { String action = canonicalAction(step.action()); if (!ACTIONS.contains(action)) throw stepError(step, "action", "invalid_step_action", "Unsupported test step action"); boolean locatorRequired = LOCATOR_ACTIONS.contains(action) || ("WAIT".equals(action) && step.locatorType() != null && !step.locatorType().isBlank()); if (complete && locatorRequired && (step.locatorType() == null || step.locatorType().isBlank() || step.locatorValue() == null || step.locatorValue().isBlank())) throw stepError(step, "locatorValue", "locator_required", "This action requires a locator"); if (step.locatorType() != null && !step.locatorType().isBlank() && !LOCATOR_TYPES.contains(step.locatorType().trim().toUpperCase(Locale.ROOT))) throw stepError(step, "locatorType", "invalid_locator_type", "Unsupported locator type"); if (step.locatorIndex() != null && step.locatorIndex() < 0) throw stepError(step, "locatorIndex", "invalid_locator_index", "Locator index must be zero or greater"); if (complete && step.locatorIndex() != null && (step.locatorType() == null || step.locatorType().isBlank() || step.locatorValue() == null || step.locatorValue().isBlank())) throw stepError(step, "locatorIndex", "invalid_locator_index", "Locator index requires a locator"); validateContextSettings(step, complete); if (complete && Set.of("NAVIGATE", "PRESS").contains(action) && (step.inputValue() == null || step.inputValue().isBlank())) throw stepError(step, "inputValue", "input_required", "This action requires an input value"); if (complete && "ASSERT_ATTRIBUTE".equals(action) && (step.inputValue() == null || step.inputValue().isBlank())) throw stepError(step, "inputValue", "attribute_name_required", "ASSERT_ATTRIBUTE requires an attribute name"); if (complete && Set.of("ASSERT_TEXT_EQUALS", "ASSERT_TEXT_CONTAINS", "ASSERT_VALUE", "ASSERT_ATTRIBUTE", "ASSERT_URL_CONTAINS", "ASSERT_URL_EQUALS", "ASSERT_COUNT").contains(action) && (step.expectedValue() == null || step.expectedValue().isBlank())) throw stepError(step, "expectedValue", "expected_value_required", "This assertion requires an expected value"); if ("ASSERT_COUNT".equals(action) && step.expectedValue() != null && !step.expectedValue().isBlank()) { try { if (Integer.parseInt(step.expectedValue().trim()) < 0) throw new NumberFormatException(); } catch (NumberFormatException ex) { throw stepError(step, "expectedValue", "invalid_expected_count", "ASSERT_COUNT expected value must be a non-negative integer"); } } }
    private static void validateContextSettings(ProjectDtos.StepRequest step, boolean complete) { boolean hasWidth = step.viewportWidth() != null; boolean hasHeight = step.viewportHeight() != null; if (complete && hasWidth != hasHeight) throw stepError(step, "viewportWidth", "viewport_dimensions_required", "Viewport width and height must be provided together"); if ((hasWidth && (step.viewportWidth() < 320 || step.viewportWidth() > 3840)) || (hasHeight && (step.viewportHeight() < 240 || step.viewportHeight() > 2160))) throw stepError(step, "viewportWidth", "invalid_viewport", "Viewport must be between 320x240 and 3840x2160"); if (step.locale() != null && !step.locale().isBlank() && java.util.Locale.forLanguageTag(step.locale().trim()).getLanguage().isBlank()) throw stepError(step, "locale", "invalid_locale", "Locale must be a valid BCP-47 language tag"); if (step.timezoneId() != null && !step.timezoneId().isBlank()) { try { java.time.ZoneId.of(step.timezoneId().trim()); } catch (java.time.DateTimeException ex) { throw stepError(step, "timezoneId", "invalid_timezone", "Timezone must be a valid IANA timezone id"); } } }
    private static boolean hasContextSettings(ProjectDtos.StepRequest step) { return step.viewportWidth() != null || step.viewportHeight() != null || (step.locale() != null && !step.locale().isBlank()) || (step.timezoneId() != null && !step.timezoneId().isBlank()); }
    private static void validateCase(ProjectDtos.CaseRequest r, String caseStatus) { if (r.retryCount() != null && (r.retryCount() < 0 || r.retryCount() > 5)) throw error(HttpStatus.BAD_REQUEST, "invalid_retry_count", "Retry count must be between 0 and 5"); if ("READY".equals(caseStatus)) { List<ProjectDtos.StepRequest> readySteps = r.steps() == null ? List.of() : r.steps(); if (readySteps.isEmpty()) throw error(HttpStatus.BAD_REQUEST, "ready_steps_required", "A READY case must contain at least one step"); ProjectDtos.StepRequest first = readySteps.stream().min(Comparator.comparingInt(ProjectDtos.StepRequest::position)).orElseThrow(); if (!"NAVIGATE".equalsIgnoreCase(canonicalAction(first.action()))) throw stepError(first, "action", "ready_must_start_navigate", "The first READY step must be NAVIGATE"); if (readySteps.stream().anyMatch(step -> "WAIT".equalsIgnoreCase(step.action()) && (step.locatorType() == null || step.locatorType().isBlank()))) throw error(HttpStatus.BAD_REQUEST, "legacy_wait_requires_edit", "Legacy unqualified WAIT steps must be edited to WAIT_VISIBLE or WAIT_HIDDEN before a case can run"); } }
    private TestSuiteEntity suite(UUID projectId, UUID id) { return suites.findByIdAndProjectId(id, projectId).orElseThrow(() -> error(HttpStatus.NOT_FOUND, "suite_not_found", "Suite was not found")); }
    private TestSuiteEntity activeSuite(UUID projectId, UUID id) { TestSuiteEntity suite = suite(projectId, id); if ("ARCHIVED".equals(suite.getStatus())) throw error(HttpStatus.CONFLICT, "suite_archived", "Archived suites are read-only"); return suite; }
    private TestCaseEntity testCase(UUID suiteId, UUID id) { return cases.findByIdAndSuiteId(id, suiteId).orElseThrow(() -> error(HttpStatus.NOT_FOUND, "case_not_found", "Case was not found")); }
    private ProjectDtos.SuiteResponse suiteResponse(TestSuiteEntity s) { return new ProjectDtos.SuiteResponse(s.getId(), s.getProject().getId(), s.getName(), s.getDescription(), s.getStatus(), s.getVersion(), s.getArchivedAt(), s.getArchivedBy() == null ? null : s.getArchivedBy().getId()); }
    private ProjectDtos.CaseResponse caseResponse(TestCaseEntity c) { return new ProjectDtos.CaseResponse(c.getId(), c.getSuite().getId(), c.getName(), c.getDescription(), c.getStatus(), c.getPriority(), c.getTags(), c.getRetryCount(), c.isDataIsolation(), c.getVersion(), steps.findByTestCaseIdOrderByPositionAsc(c.getId()).stream().map(s -> new ProjectDtos.StepResponse(s.getId(), s.getPosition(), s.getAction(), s.getLocatorType(), s.getLocatorValue(), s.getLocatorRole(), s.getLocatorIndex(), s.getInputValue(), s.getExpectedValue(), s.getTimeoutMs(), s.getViewportWidth(), s.getViewportHeight(), s.getLocale(), s.getTimezoneId())).toList(), c.getArchivedAt(), c.getArchivedBy() == null ? null : c.getArchivedBy().getId()); }
    private static String canonicalAction(String value) { String action = value == null ? "" : value.trim().toUpperCase(Locale.ROOT); return switch (action) { case "SELECT" -> "SELECT_OPTION"; case "ASSERT_TEXT" -> "ASSERT_TEXT_CONTAINS"; default -> action; }; }
    private static String status(String value) { String v = value == null ? "DRAFT" : value.trim().toUpperCase(Locale.ROOT); if (!Set.of("DRAFT", "READY").contains(v)) throw error(HttpStatus.BAD_REQUEST, "invalid_case_status", "Status must be DRAFT or READY; use the trash operation to archive a case"); return v; }
    private static String priority(String value) { String v = value == null ? "MEDIUM" : value.trim().toUpperCase(Locale.ROOT); if (!Set.of("LOW", "MEDIUM", "HIGH", "CRITICAL").contains(v)) throw error(HttpStatus.BAD_REQUEST, "invalid_case_priority", "Priority is invalid"); return v; }
    private static void requireVersion(long current, Long expected) { if (expected != null && current != expected) throw error(HttpStatus.CONFLICT, "stale_version", "The resource changed; reload and try again"); }
    private static void ensureActive(ProjectEntity p) { if ("ARCHIVED".equals(p.getStatus())) throw error(HttpStatus.CONFLICT, "project_archived", "Archived projects are read-only"); }
    private static String trim(String v) { return v == null ? null : v.trim(); }
    private List<TestSuiteEntity> findSuites(UUID projectId, String lifecycle) { return switch (lifecycle) { case "ACTIVE" -> suites.findByProjectIdAndStatusNotOrderByNameAsc(projectId, "ARCHIVED"); case "ARCHIVED" -> suites.findByProjectIdAndStatusOrderByNameAsc(projectId, "ARCHIVED"); default -> suites.findByProjectIdOrderByNameAsc(projectId); }; }
    private List<TestCaseEntity> findCases(UUID suiteId, String lifecycle) { return switch (lifecycle) { case "ACTIVE" -> cases.findBySuiteIdAndStatusNotOrderByNameAsc(suiteId, "ARCHIVED"); case "ARCHIVED" -> cases.findBySuiteIdAndStatusOrderByNameAsc(suiteId, "ARCHIVED"); default -> cases.findBySuiteIdOrderByNameAsc(suiteId); }; }
    private boolean activeSuiteNameExists(UUID projectId, String name) { return suites.existsByProjectIdAndNameIgnoreCaseAndStatusNot(projectId, name, "ARCHIVED"); }
    private boolean activeCaseNameExists(UUID suiteId, String name) { return cases.existsBySuiteIdAndNameIgnoreCaseAndStatusNot(suiteId, name, "ARCHIVED"); }
    private static String lifecycle(String value) { String lifecycle = value == null ? "ACTIVE" : value.trim().toUpperCase(Locale.ROOT); if (!Set.of("ACTIVE", "ARCHIVED", "ALL").contains(lifecycle)) throw error(HttpStatus.BAD_REQUEST, "invalid_lifecycle", "Lifecycle must be ACTIVE, ARCHIVED, or ALL"); return lifecycle; }
    private static String restoredName(String requested, String current, int maxLength) { String value = requested == null || requested.isBlank() ? current : requested.trim(); if (value.length() > maxLength) throw error(HttpStatus.BAD_REQUEST, "restore_name_too_long", "Restore name is too long"); return value; }
    private static ApiException error(HttpStatus status, String code, String message) { return new ApiException(status, code, message); }
    private static ApiException stepError(ProjectDtos.StepRequest step, String field, String code, String message) { return new ApiException(HttpStatus.BAD_REQUEST, code, message, "steps[" + step.position() + "]." + field, step.position()); }
}
